# Generated by Django 3.2.5 on 2022-04-23 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0002_auto_20170318_0000'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
